### ISSUE TITLE
TypeError: r.scrollIntoView is not a function

### ISSUE THREAD

**Issue by gardner** [kaiostech/sample-react#5]
Due to https://github.com/kaiostech/sample-react/issues/4, I had to remove `kdeploy` from `package.json` to get `npm install` to finish. Then I loaded the app on a _Nokia 8110 4G_. The app opens on the device and appears blank. The console log shows:

    TypeError: r.scrollIntoView is not a function
    Stack trace:
    h/i/<@app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/main.0f7060ee.chunk.js:1:2634
    h/i@app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/main.0f7060ee.chunk.js:1:2521
    h/o@app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/main.0f7060ee.chunk.js:1:2084
    h/<@app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/main.0f7060ee.chunk.js:1:1843
    yo@app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/2.a435d0bc.chunk.js:1:86745
    Ru@app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/2.a435d0bc.chunk.js:1:111781
    t.unstable_runWithPriority@app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/2.a435d0bc.chunk.js:1:129446
    Ql@app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/2.a435d0bc.chunk.js:1:54204
    Iu@app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/2.a435d0bc.chunk.js:1:111536
    Mu/<@app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/2.a435d0bc.chunk.js:1:111448
    j@app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/2.a435d0bc.chunk.js:1:128827
    T.port1.onmessage@app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/2.a435d0bc.chunk.js:1:127573
    
        at mo (app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/2.a435d0bc.chunk.js:1:86027)
        at Co/n.callback (app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/2.a435d0bc.chunk.js:1:91906)
        at ka (app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/2.a435d0bc.chunk.js:1:58715)
        at wa (app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/2.a435d0bc.chunk.js:1:58453)
        at zu/< (app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/2.a435d0bc.chunk.js:1:110373)
        at t.unstable_runWithPriority (app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/2.a435d0bc.chunk.js:1:129446)
        at Ql (app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/2.a435d0bc.chunk.js:1:54204)
        at zu (app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/2.a435d0bc.chunk.js:1:106400)
        at gu (app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/2.a435d0bc.chunk.js:1:96698)
        at Xl/< (app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/2.a435d0bc.chunk.js:1:54494)
        at t.unstable_runWithPriority (app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/2.a435d0bc.chunk.js:1:129446)
        at Ql (app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/2.a435d0bc.chunk.js:1:54204)
        at Xl (app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/2.a435d0bc.chunk.js:1:54440)
        at Yl (app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/2.a435d0bc.chunk.js:1:54375)
        at Ru (app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/2.a435d0bc.chunk.js:1:111891)
        at t.unstable_runWithPriority (app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/2.a435d0bc.chunk.js:1:129446)
        at Ql (app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/2.a435d0bc.chunk.js:1:54204)
        at Iu (app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/2.a435d0bc.chunk.js:1:111536)
        at Mu/< (app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/2.a435d0bc.chunk.js:1:111448)
        at j (app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/2.a435d0bc.chunk.js:1:128827)
        at T.port1.onmessage (app://3c19fe70-189c-5141-a97c-3625bf7d76e9/static/js/2.a435d0bc.chunk.js:1:127573) 2.a435d0bc.chunk.js:1:86027

![image](https://user-images.githubusercontent.com/787026/67437950-a8b7a380-f64e-11e9-9876-8430377ac671.png)

**Comment by Losses** [comment]
I'm also trying to develop application for KaiOS, but it seems the developer team never cares about its development community, nobody read your issue, nobody fix the bugs... What a sad story :(

**Comment by kiranj986** [comment]
Update following  function  in userNavigation.js 

`const selectElement = (selectElement, setIndex = 0) => {
    if (selectElement) {
      [].forEach.call(getAllElements(), (element, index) => {
        const selectThisElement = element;
        element.setAttribute("nav-selected", element === selectElement);
        element.setAttribute("nav-index", index);
        if (selectThisElement) {
          selectThisElement.scrollIntoView(true);
          if (element.nodeName === 'INPUT') {
            element.focus();
          } else {
            element.blur();
          }
        }
      });
      setCurrent({ type: selectElement.tagName, index: setIndex });
    } else {
      setNavigation(0);
    }
  }`

**Comment by Urhengulas** [comment]
I guess this issue can be closed then?
_(If there is a maintainer...)_
